apiVersion: v1
kind: Secret
metadata:
  labels:
    hypershift.openshift.io/safe-to-delete-with-cluster: "true"
  name: {{ .Values.name }}-etcd-encryption-key
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  key: {{ .Values.etcdEncryptionKey }}
