{{- if .Values.github }}
apiVersion: v1
kind: Secret
metadata:
  name: "hcp-{{ .Values.name }}-github-oauth-idp"
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  "clientID": {{ .Values.github.clientID }}
  "clientSecret": {{ .Values.github.clientSecret }}
{{ end }}