apiVersion: v1
kind: Secret
metadata:
  name: "{{ .Values.name }}-vault-approle-secret"
  namespace: policies
type: Opaque
stringData:
  "role_id": {{ .Values.vault.roleID }}
  "secret_id": {{ .Values.vault.secretID }}
