name: test-cluster
namespace: clusters
providerDomain: "" # optional
publicDomain: ""
publicZoneID: ""
privateZoneID: ""
oidcURL: ""
etcdEncryptionKey: "" # value should be base64 encoded
vpcID: ""
vpcCidrBlocks: []
subnetID: ""
zone: ""
region: ""
pullSecret: "hypershift-pull-secret"
sshKey: "hypershift-ssh-key"
releaseImage: "quay.io/openshift-release-dev/ocp-release:4.14.10-multi-x86_64"

roles:
  controlPlaneOperator: ""
  imageRegistry: ""
  ingress: ""
  cloudController: ""
  network: ""
  nodePool: ""
  storage: ""

workers:
  number: 1
  instanceType: "t3a.xlarge"
  profile: ""
  securityGroup: ""

vault:
  roleID: ""
  secretID: ""

github:
  clientID: ""
  clientSecret: ""
  teams: []

managedClusterSet: ""
managedClusterExtraLabels: []
